// ============================================================
// build.js — Auto-generate env-config.js from Vercel env vars
// Runs during Vercel build. Also works locally with .env file.
// ============================================================

const fs = require('fs');
const path = require('path');

// Load .env file if it exists (for local dev)
const envFilePath = path.join(__dirname, '.env');
if (fs.existsSync(envFilePath)) {
    const envContent = fs.readFileSync(envFilePath, 'utf8');
    envContent.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) return;
        const [key, ...valueParts] = trimmed.split('=');
        const value = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
        if (key && !process.env[key.trim()]) {
            process.env[key.trim()] = value;
        }
    });
    console.log('📄 Loaded .env file for local dev');
}

// Build the env config object
const envConfig = {
    SUPABASE_URL: process.env.VITE_SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY || '',
    RESEND_API_KEY: process.env.VITE_RESEND_API_KEY || ''
};

// Warn if keys are missing
if (!envConfig.SUPABASE_URL || !envConfig.SUPABASE_ANON_KEY) {
    console.warn('⚠️ WARNING: SUPABASE_URL or SUPABASE_ANON_KEY missing!');
    console.warn('   - Production: Vercel env vars set karein');
    console.warn('   - Local dev: .env file banayein');
}

// Generate env-config.js
const output = `// ============================================================
// env-config.js — AUTO-GENERATED by build.js
// DO NOT EDIT MANUALLY — edit .env or Vercel env vars instead
// Generated at: ${new Date().toISOString()}
// ============================================================

window.NEXI_ENV = ${JSON.stringify(envConfig, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'env-config.js'), output);

console.log('✅ env-config.js generated successfully');
console.log('   SUPABASE_URL:', envConfig.SUPABASE_URL ? '✅ set' : '❌ missing');
console.log('   SUPABASE_ANON_KEY:', envConfig.SUPABASE_ANON_KEY ? '✅ set' : '❌ missing');
console.log('   RESEND_API_KEY:', envConfig.RESEND_API_KEY ? '✅ set (future use)' : '⏸️ not set yet');