// ============================================================
// env-config.js — AUTO-GENERATED by build.js
// DO NOT EDIT MANUALLY — edit .env or Vercel env vars instead
// Generated at: 2026-10-04T13:45:28.885Z
// ============================================================

window.NEXI_ENV = {
  "SUPABASE_URL": "https://awiduhclxuxkqkxrgfub.supabase.co",
  "SUPABASE_ANON_KEY": "sb_publishable_D44mLJQb87KSHfN_9lQTHg_hvAzRavv",
  "RESEND_API_KEY": ""
};
