// ============================================================
// Nexi Rocket-XauPo — Supabase Client Configuration
// File: supabase-config.js
// Version: v5 (Phase C — Environment Variables)
// ============================================================

// 🔐 ENV VARS — Auto-loaded from env-config.js (generated by build.js)
// Production: Vercel env vars se aate hain
// Local: .env file se aate hain
const SUPABASE_URL = (window.NEXI_ENV && window.NEXI_ENV.SUPABASE_URL) || '';
const SUPABASE_KEY = (window.NEXI_ENV && window.NEXI_ENV.SUPABASE_ANON_KEY) || '';

// ⚠️ Safety check — agar env vars load nahi hue to warn karein
if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.error('❌ CRITICAL: Supabase credentials not loaded!');
    console.error('   - Production: Check Vercel env vars');
    console.error('   - Local: Check .env file + run "node build.js"');
    console.error('   - Also: Ensure <script src="env-config.js"></script> is loaded BEFORE supabase-config.js');
}

// Supabase client (CDN se aata hai — HTML mein script tag lagayenge)
let supabaseClient = null;

// Initialize function — jab bhi zaroorat ho call karein
function initSupabase() {
    if (supabaseClient) return supabaseClient;
    if (typeof supabase === 'undefined') {
        console.error('❌ Supabase CDN not loaded!');
        return null;
    }
    if (!SUPABASE_URL || !SUPABASE_KEY) {
        console.error('❌ Cannot init Supabase — missing credentials');
        return null;
    }
    supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
    return supabaseClient;
}

// ============================================================
// SUPABASE AUTH HELPERS (Phase B2 — Migration)
// ============================================================

// ------------------------------------------------------------
// 1. SIGN UP — Naya user register karein
// ------------------------------------------------------------
async function signUpUser(email, password, metadata = {}) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: { message: 'Supabase init failed' } };

        const { data, error } = await sb.auth.signUp({
            email: email.toLowerCase().trim(),
            password: password,
            options: {
                data: metadata,
                emailRedirectTo: window.location.origin + '/payment-pending'
            }
        });

        if (error) {
            console.error('signUpUser error:', error);
            return { error };
        }

        console.log('✅ signUpUser success:', data.user?.email);
        return { data };
    } catch (err) {
        console.error('signUpUser exception:', err);
        return { error: { message: err.message || 'Unknown error' } };
    }
}

// ------------------------------------------------------------
// 2. SIGN IN — User login karein
// ------------------------------------------------------------
async function signInUser(email, password) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: { message: 'Supabase init failed' } };

        const { data, error } = await sb.auth.signInWithPassword({
            email: email.toLowerCase().trim(),
            password: password
        });

        if (error) {
            console.error('signInUser error:', error);
            return { error };
        }

        console.log('✅ signInUser success:', data.user?.email);
        return { data };
    } catch (err) {
        console.error('signInUser exception:', err);
        return { error: { message: err.message || 'Unknown error' } };
    }
}

// ------------------------------------------------------------
// 3. SIGN OUT — User logout karein
// ------------------------------------------------------------
async function signOutUser() {
    try {
        const sb = initSupabase();
        if (!sb) return { error: { message: 'Supabase init failed' } };

        const { error } = await sb.auth.signOut();
        if (error) {
            console.error('signOutUser error:', error);
            return { error };
        }

        console.log('✅ signOutUser success');
        return { success: true };
    } catch (err) {
        console.error('signOutUser exception:', err);
        return { error: { message: err.message || 'Unknown error' } };
    }
}

// ------------------------------------------------------------
// 4. GET SESSION
// ------------------------------------------------------------
async function getCurrentSession() {
    try {
        const sb = initSupabase();
        if (!sb) return null;

        const { data, error } = await sb.auth.getSession();
        if (error) {
            console.error('getCurrentSession error:', error);
            return null;
        }
        return data.session || null;
    } catch (err) {
        console.error('getCurrentSession exception:', err);
        return null;
    }
}

// ------------------------------------------------------------
// 5. GET AUTH USER
// ------------------------------------------------------------
async function getCurrentAuthUser() {
    try {
        const sb = initSupabase();
        if (!sb) return null;

        const { data, error } = await sb.auth.getUser();
        if (error) {
            console.error('getCurrentAuthUser error:', error);
            return null;
        }
        return data.user || null;
    } catch (err) {
        console.error('getCurrentAuthUser exception:', err);
        return null;
    }
}

// ------------------------------------------------------------
// 6. RESET PASSWORD (Step 10 — redirect to /reset-password)
// ------------------------------------------------------------
async function resetPassword(email) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: { message: 'Supabase init failed' } };

        const redirectUrl = window.location.origin + '/reset-password';

        const { data, error } = await sb.auth.resetPasswordForEmail(
            email.toLowerCase().trim(),
            { redirectTo: redirectUrl }
        );

        if (error) {
            console.error('resetPassword error:', error);
            return { error };
        }

        console.log('✅ resetPassword email sent:', email);
        return { data };
    } catch (err) {
        console.error('resetPassword exception:', err);
        return { error: { message: err.message || 'Unknown error' } };
    }
}

// ------------------------------------------------------------
// 7. UPDATE PASSWORD
// ------------------------------------------------------------
async function updatePassword(newPassword) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: { message: 'Supabase init failed' } };

        const { data, error } = await sb.auth.updateUser({ password: newPassword });

        if (error) {
            console.error('updatePassword error:', error);
            return { error };
        }

        console.log('✅ updatePassword success');
        return { data };
    } catch (err) {
        console.error('updatePassword exception:', err);
        return { error: { message: err.message || 'Unknown error' } };
    }
}

// ------------------------------------------------------------
// 8. ON AUTH STATE CHANGE
// ------------------------------------------------------------
function onAuthStateChange(callback) {
    try {
        const sb = initSupabase();
        if (!sb) return null;

        const { data } = sb.auth.onAuthStateChange((event, session) => {
            console.log('🔐 Auth event:', event);
            callback(event, session);
        });

        return data.subscription;
    } catch (err) {
        console.error('onAuthStateChange exception:', err);
        return null;
    }
}

// ============================================================
// END OF PART 1/3
// ============================================================

// ============================================================
// PART 2/3 — LEGACY HELPERS + RATE LIMITING
// ============================================================

// ============================================================
// HELPER FUNCTIONS — Users (Legacy)
// ============================================================

async function getUserByEmail(email) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('users')
        .select('*')
        .eq('email', email.toLowerCase())
        .maybeSingle();
    if (error) { console.error('getUserByEmail error:', error); return null; }
    return data;
}

async function getUserBySecretKey(secretKey) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('users')
        .select('*')
        .eq('secret_key', secretKey)
        .maybeSingle();
    if (error) { console.error('getUserBySecretKey error:', error); return null; }
    return data;
}

async function createUser(userData) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('users')
        .insert([userData])
        .select()
        .single();
    if (error) { console.error('createUser error:', error); return { error }; }
    return { data };
}

async function createPayment(paymentData) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('payments')
        .insert([paymentData])
        .select()
        .single();
    if (error) { console.error('createPayment error:', error); return { error }; }
    return { data };
}

async function getAllUsers() {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('users')
        .select('*')
        .order('created_at', { ascending: false });
    if (error) { console.error('getAllUsers error:', error); return []; }
    return data || [];
}

async function getAllPayments() {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('payments')
        .select('*')
        .order('created_at', { ascending: false });
    if (error) { console.error('getAllPayments error:', error); return []; }
    return data || [];
}

// ============================================================
// HELPER FUNCTIONS — Settings
// ============================================================

async function getSetting(key, defaultValue = null) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('settings')
        .select('value')
        .eq('key', key)
        .maybeSingle();
    if (error) {
        console.error('getSetting error:', error);
        return defaultValue;
    }
    return data ? data.value : defaultValue;
}

async function getSettingWithDefault(key, defaultValue = null) {
    return await getSetting(key, defaultValue);
}

async function getAllSettings() {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('settings')
        .select('*')
        .order('category', { ascending: true })
        .order('display_order', { ascending: true });
    if (error) {
        console.error('getAllSettings error:', error);
        return [];
    }
    return data || [];
}

async function updateSetting(key, value) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('settings')
        .update({ value: String(value), updated_at: new Date().toISOString() })
        .eq('key', key)
        .select()
        .single();
    if (error) {
        console.error('updateSetting error:', error);
        return { error };
    }
    return { data };
}

let _cachedFreeTrades = null;

async function getFreeTradesPerDay() {
    if (_cachedFreeTrades !== null) return _cachedFreeTrades;
    const val = await getSetting('free_trades_per_day', '3');
    _cachedFreeTrades = parseInt(val) || 3;
    return _cachedFreeTrades;
}

// ============================================================
// HELPER FUNCTIONS — Alerts
// ============================================================

async function getActiveAlerts(target = 'both') {
    const sb = initSupabase();
    let query = sb.from('alerts').select('*').eq('is_active', true).order('created_at', { ascending: false });

    if (target === 'demo') {
        query = query.in('target', ['demo', 'both']);
    } else if (target === 'clients') {
        query = query.in('target', ['clients', 'both']);
    }

    const { data, error } = await query;
    if (error) { console.error('getActiveAlerts error:', error); return []; }

    const now = new Date();
    const filtered = (data || []).filter(a => {
        if (a.start_time && new Date(a.start_time) > now) return false;
        if (a.end_time && new Date(a.end_time) < now) return false;
        return true;
    });
    return filtered;
}

async function getAllAlerts() {
    const sb = initSupabase();
    const { data, error } = await sb.from('alerts').select('*').order('created_at', { ascending: false });
    if (error) { console.error('getAllAlerts error:', error); return []; }
    return data || [];
}

async function createAlert(alertData) {
    const sb = initSupabase();
    const { data, error } = await sb.from('alerts').insert([alertData]).select().single();
    if (error) { console.error('createAlert error:', error); return { error }; }
    return { data };
}

async function updateAlert(id, updates) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('alerts')
        .update({ ...updates, updated_at: new Date().toISOString() })
        .eq('id', id)
        .select()
        .single();
    if (error) { console.error('updateAlert error:', error); return { error }; }
    return { data };
}

async function deleteAlert(id) {
    const sb = initSupabase();
    const { error } = await sb.from('alerts').delete().eq('id', id);
    if (error) { console.error('deleteAlert error:', error); return { error }; }
    return { success: true };
}

// ============================================================
// HELPER FUNCTIONS — Alert Templates
// ============================================================

async function getAllTemplates(limit = 100) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('alert_templates')
        .select('*')
        .order('last_used_at', { ascending: false, nullsFirst: false })
        .order('created_at', { ascending: false })
        .limit(limit);
    if (error) { console.error('getAllTemplates error:', error); return []; }
    return data || [];
}

async function createTemplate(templateData) {
    const sb = initSupabase();
    const { data, error } = await sb.from('alert_templates').insert([templateData]).select().single();
    if (error) { console.error('createTemplate error:', error); return { error }; }
    return { data };
}

async function updateTemplateUsage(id, currentCount) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('alert_templates')
        .update({ times_used: (currentCount || 0) + 1, last_used_at: new Date().toISOString() })
        .eq('id', id)
        .select()
        .single();
    if (error) { console.error('updateTemplateUsage error:', error); return { error }; }
    return { data };
}

async function deleteTemplate(id) {
    const sb = initSupabase();
    const { error } = await sb.from('alert_templates').delete().eq('id', id);
    if (error) { console.error('deleteTemplate error:', error); return { error }; }
    return { success: true };
}

// ============================================================
// HELPER FUNCTIONS — Publicity Banners
// ============================================================

async function getActiveBanners(target = 'both') {
    const sb = initSupabase();
    let query = sb.from('publicity_banners').select('*').eq('is_active', true).order('created_at', { ascending: false });

    if (target === 'demo') {
        query = query.in('target', ['demo', 'both']);
    } else if (target === 'clients') {
        query = query.in('target', ['clients', 'both']);
    }

    const { data, error } = await query;
    if (error) { console.error('getActiveBanners error:', error); return []; }

    const now = new Date();
    const filtered = (data || []).filter(b => {
        if (b.start_time && new Date(b.start_time) > now) return false;
        if (b.end_time && new Date(b.end_time) < now) return false;
        return true;
    });
    return filtered;
}

async function getAllBanners() {
    const sb = initSupabase();
    const { data, error } = await sb.from('publicity_banners').select('*').order('created_at', { ascending: false });
    if (error) { console.error('getAllBanners error:', error); return []; }
    return data || [];
}

async function createBanner(bannerData) {
    const sb = initSupabase();
    const { data, error } = await sb.from('publicity_banners').insert([bannerData]).select().single();
    if (error) { console.error('createBanner error:', error); return { error }; }
    return { data };
}

async function updateBanner(id, updates) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('publicity_banners')
        .update({ ...updates, updated_at: new Date().toISOString() })
        .eq('id', id)
        .select()
        .single();
    if (error) { console.error('updateBanner error:', error); return { error }; }
    return { data };
}

async function deleteBanner(id) {
    const sb = initSupabase();
    const { error } = await sb.from('publicity_banners').delete().eq('id', id);
    if (error) { console.error('deleteBanner error:', error); return { error }; }
    return { success: true };
}

// ============================================================
// HELPER FUNCTIONS — Banner Templates
// ============================================================

async function getBannerTemplates(limit = 100) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('banner_templates')
        .select('*')
        .order('last_used_at', { ascending: false, nullsFirst: false })
        .order('created_at', { ascending: false })
        .limit(limit);
    if (error) { console.error('getBannerTemplates error:', error); return []; }
    return data || [];
}

async function saveBannerTemplate(templateData) {
    const sb = initSupabase();
    const { data, error } = await sb.from('banner_templates').insert([templateData]).select().single();
    if (error) { console.error('saveBannerTemplate error:', error); return { error }; }
    return { data };
}

async function updateBannerTemplateUsage(id, currentCount) {
    const sb = initSupabase();
    const { data, error } = await sb
        .from('banner_templates')
        .update({ times_used: (currentCount || 0) + 1, last_used_at: new Date().toISOString() })
        .eq('id', id)
        .select()
        .single();
    if (error) { console.error('updateBannerTemplateUsage error:', error); return { error }; }
    return { data };
}

async function deleteBannerTemplate(id) {
    const sb = initSupabase();
    const { error } = await sb.from('banner_templates').delete().eq('id', id);
    if (error) { console.error('deleteBannerTemplate error:', error); return { error }; }
    return { success: true };
}

// ============================================================
// 🆕 RATE LIMITING HELPERS (Phase B4)
// ============================================================

async function checkRateLimit(identifier, action, maxAttempts = 5, windowSeconds = 60, blockSeconds = 900) {
    try {
        const sb = initSupabase();
        if (!sb) return { allowed: false, error: 'Supabase init failed' };

        const { data, error } = await sb.rpc('check_rate_limit', {
            p_identifier: identifier,
            p_action: action,
            p_max_attempts: maxAttempts,
            p_window_seconds: windowSeconds,
            p_block_seconds: blockSeconds
        });

        if (error) {
            console.error('checkRateLimit error:', error);
            return { allowed: true, error: error.message };
        }
        return data;
    } catch (err) {
        console.error('checkRateLimit exception:', err);
        return { allowed: true, error: err.message };
    }
}

const RATE_LIMIT_PRESETS = {
    login:          { max: 5, window: 60, block: 900 },
    register:       { max: 3, window: 300, block: 1800 },
    password_reset: { max: 2, window: 600, block: 3600 },
    resend_email:   { max: 1, window: 300, block: 1800 },
    payment_submit: { max: 3, window: 1800, block: 3600 },
    contact_form:   { max: 2, window: 600, block: 3600 }
};

async function checkRateLimitFor(action, identifier) {
    const preset = RATE_LIMIT_PRESETS[action] || RATE_LIMIT_PRESETS.login;
    return await checkRateLimit(identifier, action, preset.max, preset.window, preset.block);
}

function formatRateLimitMessage(result) {
    if (!result) return '❌ Too many attempts. Please try again later.';
    const seconds = result.seconds_remaining || 0;
    const minutes = Math.floor(seconds / 60);
    const secs = seconds % 60;
    let timeStr = '';
    if (minutes > 0) timeStr = minutes + ' minute' + (minutes > 1 ? 's' : '');
    if (secs > 0) timeStr += (timeStr ? ' ' : '') + secs + ' second' + (secs > 1 ? 's' : '');
    if (!timeStr) timeStr = 'a few minutes';
    return `🚫 Too many attempts!\n\nPlease wait ${timeStr} before trying again.`;
}

// ============================================================
// END OF PART 2/3
// ============================================================

// ============================================================
// PART 3/3 — NEW HELPERS + SESSION TIMEOUT
// ============================================================

// ============================================================
// HELPER FUNCTIONS — Visits
// ============================================================

async function logVisit(page = 'index', ipAddress = null) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };

        const today = new Date().toISOString().split('T')[0];
        const ua = navigator.userAgent || '';
        const payload = { page: page, user_agent: ua, visited_date: today };
        if (ipAddress) payload.ip_address = ipAddress;

        const { data, error } = await sb.from('visits').insert([payload]).select().single();
        if (error) { console.error('logVisit error:', error); return { error }; }
        return { data };
    } catch (err) {
        console.error('logVisit exception:', err);
        return { error: err };
    }
}

async function getTodayVisits() {
    try {
        const sb = initSupabase();
        if (!sb) return 0;
        const today = new Date().toISOString().split('T')[0];
        const { count, error } = await sb.from('visits').select('*', { count: 'exact', head: true }).eq('visited_date', today);
        if (error) { console.error('getTodayVisits error:', error); return 0; }
        return count || 0;
    } catch (err) {
        console.error('getTodayVisits exception:', err);
        return 0;
    }
}

async function getVisitsGroupedByDate(limit = 30) {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        const { data, error } = await sb.from('visits').select('visited_date, ip_address').order('visited_date', { ascending: false }).limit(5000);
        if (error) { console.error('getVisitsGroupedByDate error:', error); return []; }

        const grouped = {};
        (data || []).forEach(v => {
            if (!v.visited_date) return;
            if (!grouped[v.visited_date]) grouped[v.visited_date] = { total: 0, ips: new Set() };
            grouped[v.visited_date].total++;
            if (v.ip_address) grouped[v.visited_date].ips.add(v.ip_address);
        });

        return Object.keys(grouped).sort().reverse().slice(0, limit).map(date => ({
            stat_date: date,
            total_visits: grouped[date].total,
            unique_visitors: grouped[date].ips.size
        }));
    } catch (err) {
        console.error('getVisitsGroupedByDate exception:', err);
        return [];
    }
}

// ============================================================
// HELPER FUNCTIONS — Daily Stats
// ============================================================

async function getDailyStats(limit = 30) {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        const { data, error } = await sb.from('daily_stats').select('*').order('stat_date', { ascending: false }).limit(limit);
        if (error) { console.error('getDailyStats error:', error); return []; }
        return data || [];
    } catch (err) {
        console.error('getDailyStats exception:', err);
        return [];
    }
}

async function saveDailyStats(statsData) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };
        const payload = { ...statsData, updated_at: new Date().toISOString() };
        const { data, error } = await sb.from('daily_stats').upsert([payload], { onConflict: 'stat_date' }).select().single();
        if (error) { console.error('saveDailyStats error:', error); return { error }; }
        return { data };
    } catch (err) {
        console.error('saveDailyStats exception:', err);
        return { error: err };
    }
}

async function getOverallWinRate(days = 30) {
    try {
        const sb = initSupabase();
        if (!sb) return '0%';
        const { data, error } = await sb.from('daily_stats').select('win_trades, total_trades').order('stat_date', { ascending: false }).limit(days);
        if (error) { console.error('getOverallWinRate error:', error); return '0%'; }

        let totWins = 0, totTrades = 0;
        (data || []).forEach(d => {
            totWins += parseInt(d.win_trades) || 0;
            totTrades += parseInt(d.total_trades) || 0;
        });
        return totTrades > 0 ? ((totWins / totTrades) * 100).toFixed(1) + '%' : '0%';
    } catch (err) {
        console.error('getOverallWinRate exception:', err);
        return '0%';
    }
}

// ============================================================
// HELPER FUNCTIONS — Signals
// ============================================================

async function getActiveSignals(target = 'clients', limit = 10) {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        let query = sb.from('signals').select('*').eq('is_active', true).order('created_at', { ascending: false }).limit(limit);

        if (target === 'demo') {
            query = query.in('target', ['demo', 'both']);
        } else if (target === 'clients') {
            query = query.in('target', ['clients', 'both']);
        }

        const { data, error } = await query;
        if (error) { console.error('getActiveSignals error:', error); return []; }
        return data || [];
    } catch (err) {
        console.error('getActiveSignals exception:', err);
        return [];
    }
}

async function getAllSignals() {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        const { data, error } = await sb.from('signals').select('*').order('created_at', { ascending: false });
        if (error) { console.error('getAllSignals error:', error); return []; }
        return data || [];
    } catch (err) {
        console.error('getAllSignals exception:', err);
        return [];
    }
}

async function getTotalSignalsCount() {
    try {
        const sb = initSupabase();
        if (!sb) return 0;
        const { count, error } = await sb.from('signals').select('*', { count: 'exact', head: true });
        if (error) { console.error('getTotalSignalsCount error:', error); return 0; }
        return count || 0;
    } catch (err) {
        console.error('getTotalSignalsCount exception:', err);
        return 0;
    }
}

// ============================================================
// HELPER FUNCTIONS — Clients Count
// ============================================================

async function getActiveClientsCount() {
    try {
        const sb = initSupabase();
        if (!sb) return 0;
        const { count, error } = await sb.from('users').select('*', { count: 'exact', head: true }).eq('status', 'active');
        if (error) { console.error('getActiveClientsCount error:', error); return 0; }
        return count || 0;
    } catch (err) {
        console.error('getActiveClientsCount exception:', err);
        return 0;
    }
}

async function getTotalClientsCount() {
    try {
        const sb = initSupabase();
        if (!sb) return 0;
        const { count, error } = await sb.from('users').select('*', { count: 'exact', head: true });
        if (error) { console.error('getTotalClientsCount error:', error); return 0; }
        return count || 0;
    } catch (err) {
        console.error('getTotalClientsCount exception:', err);
        return 0;
    }
}

// ============================================================
// HELPER FUNCTIONS — Trades
// ============================================================

async function getTradesBetween(startISO, endISO) {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        const { data, error } = await sb.from('trades').select('profit, exit, created_at')
            .gte('created_at', startISO).lte('created_at', endISO).not('exit', 'is', null);
        if (error) { console.error('getTradesBetween error:', error); return []; }
        return data || [];
    } catch (err) {
        console.error('getTradesBetween exception:', err);
        return [];
    }
}

// ============================================================
// VERSION LOG
// ============================================================
console.log('✅ supabase-config.js v5 loaded — ENV + Auth + Legacy + RateLimit + Session');

// ============================================================
// SESSION TIMEOUT SYSTEM (B6)
// ============================================================

const SESSION_CONFIG = {
    TIMEOUT_MINUTES: 30,
    WARNING_BEFORE_SECONDS: 60,
    ACTIVITY_EVENTS: ['click', 'keydown', 'mousemove', 'scroll', 'touchstart'],
    CHECK_INTERVAL_SECONDS: 10
};

let _sessionState = {
    lastActivity: Date.now(),
    warningShown: false,
    timeoutTimer: null,
    warningTimer: null,
    intervalTimer: null,
    active: false,
    onLogout: null,
    warningElement: null
};

function initSessionTimeout(onLogoutCallback, redirectUrl = 'signin.html') {
    if (_sessionState.active) return;
    _sessionState.active = true;
    _sessionState.lastActivity = Date.now();
    _sessionState.onLogout = onLogoutCallback || function() {
        localStorage.removeItem('nexiCurrentUser');
        sessionStorage.removeItem('nexiAdmin');
        alert('⏰ Session expired — 30 minutes of inactivity.\n\nPlease login again.');
        window.location.replace(redirectUrl);
    };
    createWarningElement();
    SESSION_CONFIG.ACTIVITY_EVENTS.forEach(event => {
        document.addEventListener(event, handleUserActivity, { passive: true });
    });
    document.addEventListener('visibilitychange', handleVisibilityChange);
    _sessionState.intervalTimer = setInterval(checkSession, SESSION_CONFIG.CHECK_INTERVAL_SECONDS * 1000);
    console.log('✅ Session timeout initialized — 30 min inactivity');
}

function handleUserActivity() {
    if (!_sessionState.active) return;
    _sessionState.lastActivity = Date.now();
    if (_sessionState.warningShown) hideWarning();
}

function handleVisibilityChange() {
    if (!document.hidden && _sessionState.active) checkSession();
}

function checkSession() {
    if (!_sessionState.active) return;
    const now = Date.now();
    const elapsed = now - _sessionState.lastActivity;
    const timeoutMs = SESSION_CONFIG.TIMEOUT_MINUTES * 60 * 1000;
    const warningMs = timeoutMs - (SESSION_CONFIG.WARNING_BEFORE_SECONDS * 1000);
    if (elapsed >= timeoutMs) {
        destroySessionTimeout();
        _sessionState.onLogout();
        return;
    }
    if (elapsed >= warningMs && !_sessionState.warningShown) showWarning();
}

function createWarningElement() {
    if (_sessionState.warningElement) return;
    const el = document.createElement('div');
    el.id = 'sessionWarningOverlay';
    el.style.cssText = `display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.85);z-index:99999;align-items:center;justify-content:center;padding:20px;`;
    el.innerHTML = `<div style="background:#111827;border:3px solid #fbbf24;border-radius:20px;padding:35px;max-width:450px;width:100%;text-align:center;box-shadow:0 20px 60px rgba(251,191,36,0.4);font-family:'Segoe UI',Roboto,sans-serif;">
        <div style="font-size:3rem;margin-bottom:15px;">⏰</div>
        <h2 style="color:#fbbf24;font-size:1.5rem;margin-bottom:15px;">Session Expiring!</h2>
        <p style="color:#cbd5e1;margin-bottom:10px;font-size:0.95rem;line-height:1.6;">Aap <strong style="color:#fbbf24;">30 minutes</strong> se inactive hain.</p>
        <p style="color:#cbd5e1;margin-bottom:25px;font-size:0.95rem;line-height:1.6;"><strong id="sessionCountdown" style="color:#ef4444;font-size:1.3rem;">60</strong> seconds mein logout ho jayenge.</p>
        <button id="sessionExtendBtn" style="background:linear-gradient(135deg,#10b981,#059669);color:white;padding:14px 35px;border:none;border-radius:10px;font-size:1rem;font-weight:700;cursor:pointer;margin-right:10px;">✓ Stay Logged In</button>
        <button id="sessionLogoutBtn" style="background:#ef4444;color:white;padding:14px 35px;border:none;border-radius:10px;font-size:1rem;font-weight:700;cursor:pointer;">Logout Now</button>
    </div>`;
    document.body.appendChild(el);
    document.getElementById('sessionExtendBtn').addEventListener('click', handleUserActivity);
    document.getElementById('sessionLogoutBtn').addEventListener('click', function() {
        destroySessionTimeout();
        _sessionState.onLogout();
    });
    _sessionState.warningElement = el;
}

function showWarning() {
    if (!_sessionState.warningElement) return;
    _sessionState.warningShown = true;
    const el = _sessionState.warningElement;
    el.style.display = 'flex';
    let secondsLeft = SESSION_CONFIG.WARNING_BEFORE_SECONDS;
    const countdownEl = document.getElementById('sessionCountdown');
    if (countdownEl) countdownEl.innerText = secondsLeft;
    _sessionState.warningTimer = setInterval(() => {
        secondsLeft--;
        if (countdownEl) countdownEl.innerText = secondsLeft;
        if (secondsLeft <= 0) clearInterval(_sessionState.warningTimer);
    }, 1000);
}

function hideWarning() {
    if (!_sessionState.warningElement) return;
    _sessionState.warningElement.style.display = 'none';
    _sessionState.warningShown = false;
    if (_sessionState.warningTimer) {
        clearInterval(_sessionState.warningTimer);
        _sessionState.warningTimer = null;
    }
}

function destroySessionTimeout() {
    _sessionState.active = false;
    if (_sessionState.intervalTimer) clearInterval(_sessionState.intervalTimer);
    if (_sessionState.warningTimer) clearInterval(_sessionState.warningTimer);
    SESSION_CONFIG.ACTIVITY_EVENTS.forEach(event => {
        document.removeEventListener(event, handleUserActivity);
    });
    document.removeEventListener('visibilitychange', handleVisibilityChange);
    if (_sessionState.warningElement) {
        _sessionState.warningElement.remove();
        _sessionState.warningElement = null;
    }
}

function extendSession() { handleUserActivity(); }

console.log('✅ Session timeout system loaded');

// ============================================================
// 🆕 B5: SECURE PAYMENT HELPERS (Phase B5 — Server-Side)
// ============================================================
// Ye helpers server-side validation function ko call karti hain.
// Client-side validation ab sirf UX ke liye hai — real check server pe hoti hai.
// ============================================================

// ------------------------------------------------------------
// Submit payment via secure RPC
// ------------------------------------------------------------
// @param {number} amount      — 3.00 ya 5.00
// @param {string} type        — 'first' ya 'renewal'
// @param {string} screenshotUrl — base64 data URL
// @param {string} payerUID    — Binance UID
// @returns {object}           — { success, payment_id, error, message }
async function submitPaymentSecure(amount, type, screenshotUrl, payerUID) {
    try {
        const sb = initSupabase();
        if (!sb) return { success: false, error: 'INIT_FAILED', message: 'Supabase init failed' };

        // 1. Get current auth user
        const { data: authData, error: authErr } = await sb.auth.getUser();
        if (authErr || !authData?.user) {
            return { success: false, error: 'NOT_AUTHENTICATED', message: 'Please login first' };
        }

        // 2. Validate inputs (basic — server does real check)
        if (!screenshotUrl || !screenshotUrl.startsWith('data:image')) {
            return { success: false, error: 'INVALID_SCREENSHOT', message: 'Screenshot is required (image format)' };
        }

        // 3. Calculate screenshot metadata
        const screenshotSize = screenshotUrl.length;
        const screenshotHash = await hashString(screenshotUrl);

        // 4. Get client IP (best-effort — server logs anyway)
        const clientIP = await getClientIP();

        // 5. Call secure RPC
        const { data, error } = await sb.rpc('submit_payment_secure', {
            p_amount: parseFloat(amount),
            p_type: type,
            p_screenshot_url: screenshotUrl,
            p_screenshot_hash: screenshotHash,
            p_screenshot_size: screenshotSize,
            p_payer_uid: String(payerUID).trim(),
            p_client_ip: clientIP
        });

        if (error) {
            console.error('submitPaymentSecure RPC error:', error);
            return { success: false, error: 'RPC_ERROR', message: error.message };
        }

        // RPC returns jsonb — already { success, error, message, payment_id }
        console.log('✅ submitPaymentSecure result:', data);
        return data || { success: false, error: 'UNKNOWN', message: 'No response from server' };

    } catch (err) {
        console.error('submitPaymentSecure exception:', err);
        return { success: false, error: 'EXCEPTION', message: err.message || 'Unknown error' };
    }
}

// ------------------------------------------------------------
// Hash string (SHA-256) — for duplicate screenshot detection
// ------------------------------------------------------------
async function hashString(str) {
    try {
        if (typeof crypto === 'undefined' || !crypto.subtle) {
            // Fallback: simple hash (less secure but works everywhere)
            let hash = 0;
            for (let i = 0; i < str.length; i++) {
                const char = str.charCodeAt(i);
                hash = ((hash << 5) - hash) + char;
                hash = hash & hash;
            }
            return 'simple_' + Math.abs(hash).toString(36);
        }

        const encoder = new TextEncoder();
        const data = encoder.encode(str);
        const hashBuffer = await crypto.subtle.digest('SHA-256', data);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    } catch (err) {
        console.error('hashString error:', err);
        // Ultimate fallback: timestamp-based (won't catch duplicates, but won't break)
        return 'ts_' + Date.now();
    }
}

// ------------------------------------------------------------
// Get client IP (best-effort — browser may block)
// ------------------------------------------------------------
async function getClientIP() {
    try {
        const resp = await fetch('https://api.ipify.org?format=json', { 
            method: 'GET',
            cache: 'no-store'
        });
        if (!resp.ok) return null;
        const data = await resp.json();
        return data.ip || null;
    } catch (err) {
        // Silent fail — IP is optional
        return null;
    }
}

// ------------------------------------------------------------
// Helper: Check if payment error needs specific UI handling
// ------------------------------------------------------------
function getPaymentErrorMessage(errorCode, fallbackMessage) {
    const messages = {
        'UNAUTHENTICATED':      'Please login first to submit payment',
        'USER_NOT_FOUND':       'Account not found. Please register first.',
        'BANNED':               'Your account is banned. Contact support.',
        'INVALID_AMOUNT':       'Invalid amount. Allowed: $3 or $5',
        'INVALID_TYPE':         'Invalid payment type',
        'AMOUNT_TYPE_MISMATCH': 'Amount does not match payment type',
        'MISSING_SCREENSHOT':   'Please upload payment screenshot',
        'SCREENSHOT_TOO_LARGE': 'Screenshot too large. Maximum 500KB.',
        'SCREENSHOT_TOO_SMALL': 'Screenshot too small. Upload a real image.',
        'INVALID_PAYER_UID':    'Please enter a valid Binance UID',
        'DUPLICATE_SCREENSHOT': 'This screenshot was already submitted. Upload a new one.',
        'RECENT_PAYMENT_EXISTS':'You submitted a payment recently. Please wait for admin approval.',
        'RPC_ERROR':            'Server error. Please try again.',
        'INIT_FAILED':          'Connection error. Please refresh and try again.'
    };
    return messages[errorCode] || fallbackMessage || 'Payment submission failed';
}

console.log('✅ B5 secure payment helpers loaded');

// ============================================================
// 🆕 B3: EMAIL VERIFICATION HELPERS
// ============================================================

// ------------------------------------------------------------
// Resend verification email
// ------------------------------------------------------------
// @param {string} email — User ka email
// @returns {object} — { success, error, message }
async function resendVerificationEmail(email) {
    try {
        const sb = initSupabase();
        if (!sb) return { success: false, error: 'INIT_FAILED', message: 'Supabase init failed' };

        if (!email || typeof email !== 'string') {
            return { success: false, error: 'INVALID_EMAIL', message: 'Email is required' };
        }

        const redirectUrl = window.location.origin + '/verify-email.html';

        const { data, error } = await sb.auth.resend({
            type: 'signup',
            email: email.toLowerCase().trim(),
            options: {
                emailRedirectTo: redirectUrl
            }
        });

        if (error) {
            console.error('resendVerificationEmail error:', error);
            return { success: false, error: 'RESEND_FAILED', message: error.message };
        }

        console.log('✅ Verification email resent to:', email);
        return { success: true, message: 'Verification email sent! Check your inbox.' };

    } catch (err) {
        console.error('resendVerificationEmail exception:', err);
        return { success: false, error: 'EXCEPTION', message: err.message || 'Unknown error' };
    }
}

// ------------------------------------------------------------
// Check if current user's email is verified
// ------------------------------------------------------------
// @returns {object} — { verified: boolean, user: object|null }
async function checkEmailVerified() {
    try {
        const sb = initSupabase();
        if (!sb) return { verified: false, user: null };

        const { data, error } = await sb.auth.getUser();
        if (error || !data?.user) {
            return { verified: false, user: null };
        }

        // Supabase marks email_confirmed_at when verified
        const isVerified = !!data.user.email_confirmed_at;
        return { verified: isVerified, user: data.user };

    } catch (err) {
        console.error('checkEmailVerified exception:', err);
        return { verified: false, user: null };
    }
}

console.log('✅ B3 email verification helpers loaded');

// ============================================================
// 🆕 STEP 7: Trade Time Formatting Helpers (AM/PM)
// ============================================================

// Full format: "04 Oct 2026, 05:30 PM"
function formatTradeTime(isoString) {
    if (!isoString) return '--';
    try {
        const d = new Date(isoString);
        if (isNaN(d.getTime())) return '--';

        const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
        const day = String(d.getDate()).padStart(2, '0');
        const month = months[d.getMonth()];
        const year = d.getFullYear();

        let hours = d.getHours();
        const minutes = String(d.getMinutes()).padStart(2, '0');
        const ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12;

        return `${day} ${month} ${year}, ${String(hours).padStart(2, '0')}:${minutes} ${ampm}`;
    } catch (e) {
        return '--';
    }
}

// Short format: "04 Oct, 05:30 PM"
function formatTradeTimeShort(isoString) {
    if (!isoString) return '--';
    try {
        const d = new Date(isoString);
        if (isNaN(d.getTime())) return '--';

        const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
        const day = String(d.getDate()).padStart(2, '0');
        const month = months[d.getMonth()];

        let hours = d.getHours();
        const minutes = String(d.getMinutes()).padStart(2, '0');
        const ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12;

        return `${day} ${month}, ${String(hours).padStart(2, '0')}:${minutes} ${ampm}`;
    } catch (e) {
        return '--';
    }
}

// Just time: "05:30 PM"
function formatTradeTimeOnly(isoString) {
    if (!isoString) return '--';
    try {
        const d = new Date(isoString);
        if (isNaN(d.getTime())) return '--';

        let hours = d.getHours();
        const minutes = String(d.getMinutes()).padStart(2, '0');
        const ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12;

        return `${String(hours).padStart(2, '0')}:${minutes} ${ampm}`;
    } catch (e) {
        return '--';
    }
}

console.log('✅ Step 7 helpers loaded — formatTradeTime, formatTradeTimeShort, formatTradeTimeOnly');

// ============================================================
// 🆕 STEP 11: EMAIL NOTIFICATION HELPER
// ============================================================
// Calls the Supabase Edge Function to send transactional emails
// via Resend API (server-side, API key safe).

// ------------------------------------------------------------
// Send notification email
// ------------------------------------------------------------
// @param {string} type — 'welcome' | 'payment_approved' | 'payment_rejected'
// @param {string} to — Recipient email
// @param {object} extraData — { name, amount, expiryDate, secretKey }
// @returns {object} — { success, email_id, error }
async function sendNotificationEmail(type, to, extraData = {}) {
    try {
        if (!type || !to) {
            return { success: false, error: 'Missing type or to' };
        }

        if (!SUPABASE_URL || !SUPABASE_KEY) {
            return { success: false, error: 'Supabase credentials missing' };
        }

        const FUNCTION_URL = SUPABASE_URL + '/functions/v1/send-notification-email';

        const body = {
            type: type,
            to: to,
            name: extraData.name || null,
            amount: extraData.amount || null,
            expiryDate: extraData.expiryDate || null,
            secretKey: extraData.secretKey || null
        };

        console.log('📧 Sending email:', type, 'to', to);

        const resp = await fetch(FUNCTION_URL, {
            method: 'POST',
            headers: {
                'Authorization': 'Bearer ' + SUPABASE_KEY,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(body)
        });

        const data = await resp.json();

        if (!resp.ok || !data.success) {
            console.error('sendNotificationEmail failed:', data);
            return { success: false, error: data.error || 'Send failed', details: data };
        }

        console.log('✅ Email sent:', data.email_id);
        return { success: true, email_id: data.email_id, type: data.type };

    } catch (err) {
        console.error('sendNotificationEmail exception:', err);
        return { success: false, error: err.message };
    }
}

console.log('✅ Step 11 email notification helper loaded');



// ============================================================
// 🆕 STEP 12: CONTACT FORM HELPER
// ============================================================

// ------------------------------------------------------------
// Submit contact message
// ------------------------------------------------------------
// @param {object} data — { name, email, subject, message }
// @returns {object} — { success, message_id, error }
async function submitContactMessage(data) {
    try {
        const sb = initSupabase();
        if (!sb) return { success: false, error: 'Supabase init failed' };

        // Basic validation
        if (!data.name || !data.email || !data.message) {
            return { success: false, error: 'Name, email and message are required' };
        }

        const payload = {
            name: String(data.name).trim().slice(0, 100),
            email: String(data.email).trim().toLowerCase().slice(0, 150),
            subject: data.subject ? String(data.subject).trim().slice(0, 200) : null,
            message: String(data.message).trim().slice(0, 2000),
            user_agent: navigator.userAgent || '',
            status: 'unread'
        };

        console.log('📨 Submitting contact message from:', payload.email);

        const { data: result, error } = await sb
            .from('contact_messages')
            .insert([payload])
            .select('id')
            .single();

        if (error) {
            console.error('submitContactMessage error:', error);
            return { success: false, error: error.message };
        }

        console.log('✅ Contact message saved:', result.id);
        return { success: true, message_id: result.id };

    } catch (err) {
        console.error('submitContactMessage exception:', err);
        return { success: false, error: err.message || 'Unknown error' };
    }
}

console.log('✅ Step 12 contact form helper loaded');


// ============================================================
// 🆕 STEP 13: CONTACT MESSAGES HELPERS (Admin)
// ============================================================

// Fetch all non-deleted contact messages
async function getContactMessages(limit = 200) {
    try {
        const sb = initSupabase();
        if (!sb) return [];
        const { data, error } = await sb
            .from('contact_messages')
            .select('*')
            .eq('is_deleted', false)
            .order('created_at', { ascending: false })
            .limit(limit);
        if (error) { console.error('getContactMessages error:', error); return []; }
        return data || [];
    } catch (err) {
        console.error('getContactMessages exception:', err);
        return [];
    }
}

// Mark as read
async function markContactMessageRead(id) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };
        const { error } = await sb.from('contact_messages').update({ status: 'read' }).eq('id', id);
        if (error) { console.error('markRead error:', error); return { error }; }
        return { success: true };
    } catch (err) {
        console.error('markContactMessageRead exception:', err);
        return { error: err };
    }
}

// Mark as unread
async function markContactMessageUnread(id) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };
        const { error } = await sb.from('contact_messages').update({ status: 'unread' }).eq('id', id);
        if (error) { console.error('markUnread error:', error); return { error }; }
        return { success: true };
    } catch (err) {
        console.error('markContactMessageUnread exception:', err);
        return { error: err };
    }
}

// Reply to message
async function replyToContactMessage(id, replyText) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };
        const { error } = await sb.from('contact_messages').update({
            admin_reply: replyText,
            replied_at: new Date().toISOString(),
            status: 'replied'
        }).eq('id', id);
        if (error) { console.error('reply error:', error); return { error }; }
        return { success: true };
    } catch (err) {
        console.error('replyToContactMessage exception:', err);
        return { error: err };
    }
}

// Soft delete
async function deleteContactMessage(id) {
    try {
        const sb = initSupabase();
        if (!sb) return { error: 'Supabase init failed' };
        const { error } = await sb.from('contact_messages').update({ is_deleted: true }).eq('id', id);
        if (error) { console.error('delete error:', error); return { error }; }
        return { success: true };
    } catch (err) {
        console.error('deleteContactMessage exception:', err);
        return { error: err };
    }
}

console.log('✅ Step 13 contact messages helpers loaded');  
// ============================================================
// END OF FILE (supabase-config.js v5)
// ============================================================